# Generated by Django 4.0.3 on 2022-12-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='d_day',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='d_month',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='d_year',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
