# Generated by Django 4.0.3 on 2022-12-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_profile_d_day_profile_d_month_profile_d_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='d_day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='d_month',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='d_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
