# Generated by Django 4.0.3 on 2022-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0003_alter_profile_d_day_alter_profile_d_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.CharField(default='https://media.istockphoto.com/id/1133765772/vector/person-gray-photo-placeholder-man.jpg?b=1&s=612x612&w=0&k=20&c=C-_3lBEUYkKiOC5pe6ssezQXiguoQapC9HxtChq7v8E=', max_length=100),
        ),
    ]
